export const BENTO_SEARCH = '@@bento/SEARCH'
export const BENTO_SEARCH_BEGIN = '@@bento/SEARCH_BEGIN'
export const BENTO_SEARCH_CANCEL = '@@bento/SEARCH_CANCEL'
export const BENTO_SEARCH_SUCCESS = '@@bento/SEARCH_SUCCESS'
export const BENTO_SEARCH_ERROR = '@@bento/SEARCH_ERROR'